# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "./HypercareCore"  # Path to your .NET Core project
    schedule:
      interval: "monthly"  
    open-pull-requests-limit: 6  

  - package-ecosystem: "npm"
    directory: "./UI"  
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 6  

  - package-ecosystem: "nuget"
    directory: "./BackEnd"  
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 6  

  - package-ecosystem: "nuget"
    directory: "./ServiceJobs"  
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 6  
