# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "./HypercareCore"  # Path to your .NET Core project
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    update-config:
      versioning-strategy: "lockfile-only"
      target-versions:
        - dependency-name: "*"
          versioning-strategy: "lockfile-only"
          update-type: "all"
          version-regex: "6.*"

  - package-ecosystem: "npm"
    directory: "./UI"  # Path to your Angular project
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "nuget"
    directory: "./BackEnd"  # Path to your .NET Core project
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "./ServiceJobs"  # Path to your .NET Core project
    schedule:
      interval: "weekly"
