# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "./HypercareCore"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "lockfile-only"
    target-versions:
      - dependency-name: "*"
        versioning-strategy: "lockfile-only"
        update-type: "all"
        version-regex: "6.*"

  - package-ecosystem: "npm"
    directory: "./UI"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "lockfile-only"
    target-versions:
      - dependency-name: "*"
        versioning-strategy: "lockfile-only"
        update-type: "all"
        version-regex: "^17.*"
