IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'LOGS' AND TABLE_NAME = 'ErrorLog ')
BEGIN
    CREATE TABLE LOGS.ErrorLog(
	LogID INT IDENTITY(1,1),
    LogDate DATETIME DEFAULT GETDATE(),
    ErrorMessage NVARCHAR(MAX),
    ProcedureName NVARCHAR(MAX),
    ParametersInfo NVARCHAR(MAX)
	CONSTRAINT [Pk_ErrorLog_LogID] PRIMARY KEY CLUSTERED 
        (
            [LogID] ASC
        ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    );
END