IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'LOGS' AND TABLE_NAME = 'EventLog')
BEGIN
    CREATE TABLE LOGS.EventLog(
	LogID INT IDENTITY(1,1),
    LogDate DATETIME DEFAULT GETDATE(),
    EventType NVARCHAR(MAX),
    EventDescription NVARCHAR(MAX)
	CONSTRAINT [PK_EventLog_LogID] PRIMARY KEY CLUSTERED 
        (
            [LogID] ASC
        ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY];
END