IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'LOGS' AND TABLE_NAME = 'AuditLog')
BEGIN
    CREATE TABLE LOGS.AuditLog(
	LogID INT IDENTITY(1,1),
    LogDate DATETIME DEFAULT GETDATE(),
    PerformedBy NVARCHAR(MAX),
    ActionDescription NVARCHAR(MAX)
	CONSTRAINT [PK_AuditLog_LogID] PRIMARY KEY CLUSTERED 
        (
            [LogID] ASC
        ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY];
END