IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'MASTERDATA')
BEGIN
    EXEC('CREATE SCHEMA MASTERDATA;');
END;

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'HYPERCARE')
BEGIN
    EXEC('CREATE SCHEMA HYPERCARE;');
END;
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'RBAC')
BEGIN
    EXEC('CREATE SCHEMA RBAC;');
END;
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'HISTORY')
BEGIN
    EXEC('CREATE SCHEMA HISTORY;');
END;

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'LOGS')
BEGIN
    EXEC('CREATE SCHEMA LOGS;');
END;

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'AUDIT')
BEGIN
    EXEC('CREATE SCHEMA AUDIT;');
END;