name: CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    paths:
      - '././UI**'  # Adjust the path to the Angular application

jobs:
  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Node.js CI
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  build-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build
      - name: Watch Angular App (for development)
        run: npm run watch
      - name: Run Tests
        run: npm test
      - name: Fix Linting Issues
        run: npm run lint:fix
      - name: Run TypeScript Linting
        run: npm run lint:tsc
