name: .NET PreBuild

on:
  push:
    branches: ["development"]
  pull_request_target:
    branches: ["development"]

jobs:
  database-connection-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Database Connection
        run: |
          # Replace 34.30.111.8 with the actual IP address of your database
          if nc -zv -w 3 34.30.111.8 3306; then
            echo "Database connection successful. Proceeding with tests."
          else
            echo "Database is down. Tests will be skipped."
            exit 1  # Exit with an error code to mark the job as failed
          fi

  build-and-test:
    runs-on: ubuntu-latest
    needs: database-connection-check
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        working-directory: ./BackEnd
        run: dotnet restore

      - name: Build
        working-directory: ./BackEnd
        run: dotnet build --no-restore

      - name: Test
        working-directory: ./BackEnd
        run: dotnet test --no-build --verbosity normal

  comment-on-failure:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: failure()
    steps:
      - name: Add comment to PR on failure
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"body": "CodeQL analysis failed. Please check the logs for details."}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
